var _BoB= [
           	{name:"Genesis", loc:"data/bob/genesis.txt"},
           	{name:"Exodus", loc:"data/bob/exodus.txt"},
           	{name:"Leviticus", loc:"data/bob/leviticus.txt"},
           	{name:"Numbers", loc:"data/bob/numbers.txt"},
           	{name:"Deuteronomy", loc:"data/bob/deuteronomy.txt"},
           	{name:"Joshua", loc:"data/bob/joshua.txt"},
           	{name:"Judges", loc:"data/bob/judges.txt"},
           	{name:"Ruth", loc:"data/bob/ruth.txt"},
           	{name:"1 Samuel", loc:"data/bob/1samuel.txt"},
           	{name:"2 Samuel", loc:"data/bob/2samuel.txt"},
           	{name:"1 Kings", loc:"data/bob/1kings.txt"},
           	{name:"2 Kings", loc:"data/bob/2kings.txt"},
           	{name:"1 Chronicles", loc:"data/bob/1chronicles.txt"},
           	{name:"2 Chronicles", loc:"data/bob/2chronicles.txt"},
           	{name:"Ezra", loc:"data/bob/ezra.txt"},
           	{name:"Nehemiah", loc:"data/bob/nehemiah.txt"},
           	{name:"Tobit", loc:"data/bob/tobit.txt"},
           	{name:"Judith", loc:"data/bob/judith.txt"},
           	{name:"Esther", loc:"data/bob/esther.txt"},
           	{name:"Job", loc:"data/bob/job.txt"},
           	{name:"Psalms", loc:"data/bob/psalms.txt"},
           	{name:"Proverbs", loc:"data/bob/proverbs.txt"},
           	{name:"Ecclesiastes", loc:"data/bob/ecclesiastes.txt"},
           	{name:"Song of Solomon", loc:"data/bob/songofsolomon.txt"},
           	{name:"Wisdom", loc:"data/bob/wisdom.txt"},
           	{name:"Sirach", loc:"data/bob/sirach.txt"},
           	{name:"Isaiah", loc:"data/bob/isaiah.txt"},
           	{name:"Jeremiah", loc:"data/bob/jeremiah.txt"},
           	{name:"Lamentations", loc:"data/bob/lamentations.txt"},
           	{name:"Baruch", loc:"data/bob/baruch.txt"},
           	{name:"Ezekiel", loc:"data/bob/ezekiel.txt"},
           	{name:"Daniel", loc:"data/bob/daniel.txt"},
           	{name:"Hosea", loc:"data/bob/hosea.txt"},
           	{name:"Joel", loc:"data/bob/joel.txt"},
           	{name:"Amos", loc:"data/bob/amos.txt"},
           	{name:"Obadiah", loc:"data/bob/obadiah.txt"},
           	{name:"Jonah", loc:"data/bob/jonah.txt"},
           	{name:"Micah", loc:"data/bob/micah.txt"},
           	{name:"Nahum", loc:"data/bob/nahum.txt"},
           	{name:"Habakkuk", loc:"data/bob/habakkuk.txt"},
           	{name:"Zephaniah", loc:"data/bob/zephaniah.txt"},
           	{name:"Haggai", loc:"data/bob/haggai.txt"},
           	{name:"Zechariah", loc:"data/bob/zechariah.txt"},
           	{name:"Malachi", loc:"data/bob/malachi.txt"},
           	{name:"1 Maccabees", loc:"data/bob/1maccabees.txt"},
           	{name:"2 Maccabees", loc:"data/bob/2maccabees.txt"},
           	{name:"Matthew", loc:"data/bob/matthew.txt"},
           	{name:"Mark", loc:"data/bob/mark.txt"},
           	{name:"Luke", loc:"data/bob/luke.txt"},
           	{name:"John", loc:"data/bob/john.txt"},
           	{name:"Acts of the Apostles", loc:"data/bob/acts.txt"},
           	{name:"Romans", loc:"data/bob/romans.txt"},
           	{name:"1 Corinthians", loc:"data/bob/1corin.txt"},
           	{name:"2 Corinthians", loc:"data/bob/2corin.txt"},
           	{name:"Galatians", loc:"data/bob/galatians.txt"},
           	{name:"Ephesians", loc:"data/bob/ephesians.txt"},
           	{name:"Philippians", loc:"data/bob/philippians.txt"},
           	{name:"Colossians", loc:"data/bob/colossians.txt"},
           	{name:"1 Thessalonians", loc:"data/bob/1thessalonians.txt"},
           	{name:"2 Thessalonians", loc:"data/bob/2thessalonians.txt"},
           	{name:"1 Timothy", loc:"data/bob/1timothy.txt"},
           	{name:"2 Timothy", loc:"data/bob/2timothy.txt"},
           	{name:"Titus", loc:"data/bob/titus.txt"},
           	{name:"Philemon", loc:"data/bob/philemon.txt"},
           	{name:"Hebrews", loc:"data/bob/hebrews.txt"},
           	{name:"James", loc:"data/bob/james.txt"},
           	{name:"1 Peter", loc:"data/bob/1peter.txt"},
           	{name:"2 Peter", loc:"data/bob/2peter.txt"},
           	{name:"1 John", loc:"data/bob/1john.txt"},
           	{name:"2 John", loc:"data/bob/2john.txt"},
           	{name:"3 John", loc:"data/bob/3john.txt"},
           	{name:"Jude", loc:"data/bob/jude.txt"},
           	{name:"Revelation", loc:"data/bob/revelation.txt"}
           	
           	
           ];